import type { Metadata } from "next";
import { Navigation } from "@/src/components/ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LangLayoutProps = {
  children: React.ReactNode;
};

export default function LangLayout({ children }: LangLayoutProps) {
  return (
    <>
      <Navigation />
      {children}
    </>
  );
}
